# Generated by Django 5.2.10 on 2026-04-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_catalog', '0002_repair_legacy_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinglocation',
            old_name='data_summary_file',
            new_name='data_summary',
        ),
    ]
