# Generated by Django 5.2.10 on 2026-04-14 19:36

import django.db.models.deletion
from django.db import migrations, models


def copy_product_categories_to_hosting_locations(apps, schema_editor):
    HostingLocation = apps.get_model("projects_catalog", "HostingLocation")
    HostingLocationProductType = apps.get_model("projects_catalog", "HostingLocationProductType")
    ProductType = apps.get_model("projects_catalog", "ProductType")

    product_type_category_ids = {}
    product_type_rows = ProductType.objects.values_list("id", "product_category_id")
    for product_type_id, product_category_id in product_type_rows:
        product_type_category_ids[product_type_id] = product_category_id

    hosting_location_category_ids = {}
    relation_rows = HostingLocationProductType.objects.values_list("hosting_location_id", "product_type_id")
    for hosting_location_id, product_type_id in relation_rows:
        product_category_id = product_type_category_ids.get(product_type_id)
        if product_category_id is None:
            continue

        category_ids = hosting_location_category_ids.get(hosting_location_id)
        if category_ids is None:
            category_ids = set()
            hosting_location_category_ids[hosting_location_id] = category_ids

        category_ids.add(product_category_id)

    for hosting_location in HostingLocation.objects.only("id"):
        category_ids = hosting_location_category_ids.get(hosting_location.id)
        if not category_ids:
            continue

        if len(category_ids) == 1:
            hosting_location.product_category_id = next(iter(category_ids))
            hosting_location.save(update_fields=["product_category"])


class Migration(migrations.Migration):

    dependencies = [
        ('projects_catalog', '0003_rename_data_summary_file_hostinglocation_data_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinglocation',
            name='product_category',
            field=models.ForeignKey(blank=True, db_column='product_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting_locations', to='projects_catalog.productcategory'),
        ),
        migrations.RunPython(
            copy_product_categories_to_hosting_locations,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='product_category',
        ),
    ]
