# Generated by Django 5.2.10 on 2026-04-16 09:30

from django.db import migrations, models
from django.utils.text import slugify


def _ensure_unique_slug(base_slug, used_slugs, max_length):
    normalized_base = (base_slug or "item")[:max_length].strip("-") or "item"
    candidate = normalized_base
    suffix = 2

    while candidate in used_slugs:
        suffix_str = f"-{suffix}"
        trimmed_base = normalized_base[: max_length - len(suffix_str)].strip("-") or "item"
        candidate = f"{trimmed_base}{suffix_str}"
        suffix += 1

    return candidate


def populate_slug_fields(apps, schema_editor):
    ProjectCatalogPage = apps.get_model("projects_catalog", "ProjectCatalogPage")
    HostingLocation = apps.get_model("projects_catalog", "HostingLocation")

    max_length = 255
    project_used_slugs = set()

    for project in ProjectCatalogPage.objects.order_by("id"):
        base_slug = slugify(project.project_name or "")
        if not base_slug:
            base_slug = f"project-{project.id}"

        slug_candidate = _ensure_unique_slug(base_slug, project_used_slugs, max_length)
        project_used_slugs.add(slug_candidate)
        project.slug = slug_candidate
        project.save(update_fields=["slug"])

    for location in HostingLocation.objects.order_by("id"):
        base_slug = slugify(location.data_type or "") or "resource"
        suffix = f"-{location.id}"
        base_max_length = max_length - len(suffix)
        trimmed_base = base_slug[:base_max_length].strip("-") or "resource"
        slug_candidate = f"{trimmed_base}{suffix}"
        location.slug = slug_candidate
        location.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects_catalog", "0004_remove_producttype_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostinglocation",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectcatalogpage",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, max_length=255, null=True),
        ),
        migrations.RunPython(populate_slug_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="hostinglocation",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="projectcatalogpage",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
